# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default:
	go build -tags="all_formats"

clean:
	-rm guetzli.exe
	-rm guetzli
